#!/usr/bin/env bash

# Navigation
alt - k : yabai -m window --focus west
alt - n : yabai -m window --focus south
alt - e : yabai -m window --focus north
alt - i : yabai -m window --focus east

# Focus space relative to active display
alt - 1 : yabai -m space --focus $(yabai -m query --spaces --display | jq '.[0].index')
alt - 2 : yabai -m space --focus $(yabai -m query --spaces --display | jq '.[1].index')
alt - 3 : yabai -m space --focus $(yabai -m query --spaces --display | jq '.[2].index')
alt - 4 : yabai -m space --focus $(yabai -m query --spaces --display | jq '.[3].index')
alt - 5 : yabai -m space --focus $(yabai -m query --spaces --display | jq '.[4].index')

# Create space on the active display
alt - s : yabai -m space --create

# Delete focused space and focus previous space
shift + alt - s : \
    index="$(yabai -m query --spaces | jq '.[] | select(."has-focus").index')" && \
    if [ $index -gt 1 ]; then newindex=$(expr $index - 1); else newindex=$(expr $index + 1); fi && \
    yabai -m space --destroy && \
    yabai -m space --focus "${newindex}"

# Moving windows
shift + alt - k : yabai -m window --swap west
shift + alt - n : yabai -m window --swap south
shift + alt - e : yabai -m window --swap north
shift + alt - i : yabai -m window --swap east

# Moving windows - warp
shift + alt + ctrl - k : yabai -m window --warp west
shift + alt + ctrl - n : yabai -m window --warp south
shift + alt + ctrl - e : yabai -m window --warp north
shift + alt + ctrl - i : yabai -m window --warp east

#rotate tree
alt - r : yabai -m space --rotate 90

# Move focused container to workspace
shift + alt - m : yabai -m window --space last; yabai -m space --focus last
shift + alt - p : yabai -m window --space prev; yabai -m space --focus prev
shift + alt - n : yabai -m window --space next; yabai -m space --focus next

shift + alt - 1 : index="$(yabai -m query --spaces --display | jq '.[0].index')"; yabai -m window --space "${index}"; yabai -m space --focus "${index}"
shift + alt - 2 : index="$(yabai -m query --spaces --display | jq '.[1].index')"; yabai -m window --space "${index}"; yabai -m space --focus "${index}"
shift + alt - 3 : index="$(yabai -m query --spaces --display | jq '.[2].index')"; yabai -m window --space "${index}"; yabai -m space --focus "${index}"
shift + alt - 4 : index="$(yabai -m query --spaces --display | jq '.[3].index')"; yabai -m window --space "${index}"; yabai -m space --focus "${index}"
shift + alt - 5 : index="$(yabai -m query --spaces --display | jq '.[4].index')"; yabai -m window --space "${index}"; yabai -m space --focus "${index}"

# focus monitor
hyper - 1  : yabai -m display --focus 1
hyper - 2  : yabai -m display --focus 2
hyper - 3  : yabai -m display --focus 3

# send window to monitor and follow focus
shift + cmd - 1  : yabai -m window --display 1; yabai -m display --focus 1
shift + cmd - 2  : yabai -m window --display 2; yabai -m display --focus 2
shift + cmd - 3  : yabai -m window --display 3; yabai -m display --focus 3

# Resize windows
lctrl + alt - left : yabai -m window --resize left:-100:0; yabai -m window --resize right:-100:0
lctrl + alt - down : yabai -m window --resize bottom:0:100; yabai -m window --resize top:0:100
lctrl + alt - up : yabai -m window --resize top:0:-100; yabai -m window --resize bottom:0:-100
lctrl + alt - right : yabai -m window --resize right:100:0; yabai -m window --resize left:100:0

# Move windows
alt + shift - up : yabai -m window --move rel:0:-100
alt + shift - down : yabai -m window --move rel:0:100
alt + shift - left : yabai -m window --move rel:-100:0
alt + shift - right : yabai -m window --move rel:100:0
# move focused window to (100, 200)
alt - c : yabai -m window --move abs:100:200

# Float / Unfloat window
alt - t : yabai -m window --toggle float

# toggle window split type
alt - l : yabai -m window --toggle split

# Balance out all windows both horizontally and vertically to occupy the same space
alt - b : yabai -m space --balance

# Flip the tree horizontally
alt - y : yabai -m space --mirror y-axis

# Flip the tree vertically
alt - x : yabai -m space --mirror x-axis

# Cycle windows
alt - w : yabai -m window --focus next || yabai -m window --focus first
alt + shift - w : yabai -m window --focus prev || yabai -m window --focus last

# Restart Yabai
shift + lctrl + alt + cmd - y : \
    /usr/bin/env osascript <<< \
        "display notification \"Restarting Yabai\" with title \"Yabai\""; \
    launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

# Make window native fullscreen
alt - f         : yabai -m window --toggle zoom-fullscreen
shift + alt - f : yabai -m window --toggle native-fullscreen
