# rose-pine
[colors]
foreground = "#e0def4"
background = "#191724"
cursor_bg = "#ebbcba"
cursor_border = "#ebbcba"
cursor_fg = "#191724"
selection_bg = "#2a283e"
selection_fg = "#e0def4"

ansi = ["#26233a", "#eb6f92", "#31748f", "#f6c177", "#9ccfd8", "#c4a7e7", "#ebbcba", "#e0def4"]
brights = ["#6e6a86", "#eb6f92", "#31748f", "#f6c177", "#9ccfd8", "#c4a7e7", "#ebbcba", "#e0def4"]
